# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               sxcfl.me
tagline:             '进取･坚韧･开放･影响'
description:         'feilong.cao@qq.com'
url:                 http://www.sxcfl.me
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              曹飞龙
  url:               https://caofeilong.github.io/blog/
  email:             feilong.cao@qq.com

gems: [jekyll-paginate]
# Custom vars
version:             1.0.0
